[build]
  command = "npm ci && nx build task-manager --configuration=production"
  publish = "dist/apps/task-manager/browser"

[build.environment]
  NODE_VERSION = "20.19.0"
  NX_DAEMON = "false"

[[plugins]]
package = "@netlify/angular-runtime"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200